version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  backend:
    build: .
    container_name: backend-container
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongo